name: Run Linting

on:
  pull_request:
    branches: ["master", "release/*"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Run Linting
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: ./my-webxr-app
          fail_on_error: true
          eslint_flags: ". --no-fix --max-warnings 0"
