name: Run Linting

on:
  pull_request:
    branches: ["master", "release/*"]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my-webxr-app

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Run Linting
        uses: reviewdog/action-eslint@v1
        with:
          workdir: ./my-webxr-app
          fail_on_error: true
          eslint_flags: ". --no-fix --max-warnings 0"
