# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build React App

on:
  pull_request:
    branches: ["master", "release/*"]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./my-webxr-app

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install Dependencies
        run: npm ci

      - name: Review Dependencies
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
          comment-summary-in-pr: on-failure

      - name: Build Application
        run: npm run build

      - name: Run Unit Tests
        run: npm test

  deploy:
    needs: build
    uses: ./.github/workflows/deployment.yml
    secrets: inherit